### PR TITLE
Upgrade font-awesome to v5 and add Gitter logo

### LINKED ISSUE #32: Upgrade Font-Awesome to V5
**Is your feature request related to a problem? Please describe.**
By using V4 of Font-Awesome we can't add new brand logos like Gitter.

**Describe the solution you'd like**
Upgrade the Font-Awesome version to V5.

### PR DESCRIPTION
**Pull request by janethavi**
## Purpose
Upgrade Font-Awesome version to V5
The purpose of this PR is to fix #32 #31 

## Goals
We can add new brand logos like Gitter.

## Approach
Removed old CSS files which are used inside the project and add an external CDN link with the new V5 Font-Awesome CSS file. Change the existing class names of the brands to work with V5.
Add the Gitter logo to the footer.

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Test environment
Ubuntu 18.04, Chrome, Tomcat 8.5

### CODE REVIEW

**Review by jayasanka-sack — APPROVED** [review]

**Review by Gravewalker666 — CHANGES_REQUESTED** [review]
@janethavi Great Job Mate!!
But we have to be careful not to mess up with the argon.css file. Can you please move that CSS codes to the global CSS file?

**Comment by janethavi** [comment]
> @janethavi Great Job Mate!!
> But we have to be careful not to mess up with the argon.css file. Can you please move that CSS codes to the global CSS file?

Thank you @Gravewalker666 
Other footer logo CSS classes are also in the argon.css file. Shall I move them too?

**Comment by Gravewalker666** [comment]
Just move the classes that you changed in this PR.

**Comment by janethavi** [comment]
> Just move the classes that you changed in this PR.

IMO I think it would be easy to maintain all the CSS classes related to the footer logos be in one single CSS file(either in argon.css or in global-custom.css). WDYT?

**Comment by Gravewalker666** [comment]
Did you write the other ones or were they default CSS classes that came with argon.css?
If they came by default leave them be and add your handwritten classes to the global CSS file.
If not move all the CSS classes to the global CSS.

**Comment by janethavi** [comment]
> Did you write the other ones or were they default CSS classes that came with argon.css?
> If they came by default leave them be and add your handwritten classes to the global CSS file.
> If not move all the CSS classes to the global CSS.

Someone else has handwritten the other footer-logo classes into the argon.css file.

**Comment by Gravewalker666** [comment]
> > Did you write the other ones or were they default CSS classes that came with argon.css?
> > If they came by default leave them be and add your handwritten classes to the global CSS file.
> > If not move all the CSS classes to the global CSS.
> 
> Someone else has handwritten the other footer-logo classes into the argon.css file.

Ok, Then it's alright for now. Leave them as they are, from next time onwards please try not to use default CSS files. I'm gonna merge this one since we have already done the mistake let's try not to do that again.
Happy coding!!

**Pull request merged**
